name: GitHub Pages Deployment

on:
  push:
    branches:
      - main  # replace 'main' with your default branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install sass
    
      - name: Build SCSS
        run: npx sass --source-map scss/mu_bs.scss mu_bs.css
    
      - name: Upload CSS as artifact
        uses: actions/upload-artifact@v2
        with:
          name: css-artifacts
          path: |
            mu_bs.css
            mu_bs.css.map
      
      - name: Compare CSS files
        run: |
          diff mu_bs.css public/mu_bs.css
          diff mu_bs.css.map public/mu_bs.css.map

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo a message
        run: echo 'Nothing to do...'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public